---
- name: Install NTP
  vars:
    package_Suse: ntp
    package_RedHat: chrony
    package_Debian: ntp
  package: name={{ item }} state=present
  with_items: "{{ vars['package_' + ansible_os_family] }}"


# ntp can't start in a container, hence no molecule tests
- name: Start the ntp service
  vars:
    service_Suse: ntpd
    service_RedHat: chronyd
    service_Debian: ntp
  service:
    name: "{{ vars['service_' + ansible_os_family] }}"
    state: started
    enabled: true
  tags:
    - skip-docker
